baseURL: "https://topics-actl.netlify.app" 
title: Topics in Actuarial, Insurance and Finance
theme: hugo-book
sectionPagesMenu: main

ignoreFiles: ["\\.template.Rmd$", 
"\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
disablePathToLower: yes
enableGitInfo: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    startLevel: 1
languages: 
  en:
    contentDir: content
    languageName: English
    weight: 1
menu:
  # before:
  #   - name: Name
  #     url: https://google.com
  #     weight: 10

  after:
    - name: ____Websites and forums____
      url: 
      weight: 13
    - name: Ed discussion forum
      url: https://canvas.lms.unimelb.edu.au/courses/220261/external_tools/5837?display=borderless
      weight: 15
    - name: ACTL20004 Canvas
      url: https://canvas.lms.unimelb.edu.au/courses/183926
      weight: 16
    - name: ACTL90021 Canvas
      url: https://canvas.lms.unimelb.edu.au/courses/181779
      weight: 17
    - name: Community Canvas
      url: https://canvas.lms.unimelb.edu.au/courses/220261  
      weight: 18
    - name: ___Exercises for this week____
      url: 
      weight: 19
    - name: Pre-Tutorial exercises
      url: https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/5966328
      weight: 27
    - name: Tutorial exercises (no sol)
      url: https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/5966329
      weight: 28
    - name: Tutorial exercises (sol)
      url: https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/5966330
      weight: 29
    - name: ___________Links____________
      url: 
      weight: 35 
    - name: Benjamin Avanzi
      url: https://bavanzicv.netlify.app/
      weight: 37
    - name: Let's connect on LinkedIn!
      url: https://www.linkedin.com/in/benjaminavanzi/
      weight: 38
    - name: Yuyu Chen
      url: https://yuyuchen-uw.github.io
      weight: 41
    - name: Introduction to Actuarial Studies 2021
      url: https://actl10001.netlify.app/
      weight: 42
    - name: Communicate Data with R
      url: https://communicate-data-with-r.netlify.app/
      weight: 45
    - name: Actuaries Institute info
      url: https://actuaries.asn.au/becoming-an-actuary/how-to-become-an-actuary/for-uni-students/become-a-uni-subscriber/
      weight: 50
params:
  # BookMenuBundle: /menu
  BookComments: yes
  BookLogo: 'img/PRIMARY_A_Vertical_Housed_RGB.png'
  BookDateFormat: "2 January 2006"
  # BookEditPath: edit/main/exampleSite
  BookPortableLinks: yes
  BookRepo: https://github.com/UniMelb-Actuarial
  BookSearch: true
  BookSection: docs
  BookServiceWorker: yes
  BookTheme: light
  BookToC: yes
  BookTranslatedOnly: no
