---
bookHidden: false
bookSearchExclude: false
title: "Week 5 Study Plan"
weight: 5
bibliography: ../../../../static/libraries.bib
---


<p style="font-size:18px;font-weight:bold;">Week 5</p> 

# Overview

This week, we will cover the following topics:

- Module 4, which is concerned with the calculation of IBNR claim ***amounts*** (the actual payments/costs).
- This week we focus on case estimates and chain ladder (the first two sections).
- There are some slides with the main elements, but major components of the module is with two spreadsheets, which can be downloaded [``here for Chapter 3``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/6021476) and [``here for the PPCI method``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/6021477)





See also detailed learning outcomes of 5.2 ("Liability valuations / Run-off triangles") of the CM2 syllabus, as well as CM2-B Excel examinations [``here``](../../0-subject-guide/SILO).











# Main references and lectures

<p style="font-size:12px;color: rgb(255, 0, 0);">Note: Typos and issues are being updated continuously throughout the semester. The online notes are always up-to-date, and can easily be read on a mobile device (version date is at the bottom). If you download a pdf version of the slides, a version date is also available on the first page. If you click on the link "latest slides" you will download the latest version. You can then compare the date and work out if it was updated. </p>


## Module 4


Read: [``Module 4``](../../2-reserving/m4-reserving-claim-amounts/)

Annotate: [``slides``](../../../output/24-Top-M4-lec.pdf)

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/183926/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/181779/external_tools/701)). This is where annotated slides will be made available, too.


## Module 6: Excel

Read: [``Module 6: Excel topics``](../../3-excel/m6-excel)

Annotate: [``slides``](../../../output/24-Top-M6-lec.pdf) [``spreadsheet``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/6021475) 
[``annotated slides UG``](https://canvas.lms.unimelb.edu.au/courses/183926/modules) [``annotated slides PG``](https://canvas.lms.unimelb.edu.au/courses/181779/modules)

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/183926/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/181779/external_tools/701)). This is where annotated slides will be made available, too.




<!-- ## Module 5 -->

<!-- Read: [``Module 5``](../../2-reserving/m5-reserving-combination/) -->

<!-- Annotate: [``slides``](../../../output/23-Top-M5-lec.pdf)  -->

<!-- Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/153686/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/154246/external_tools/701)). This is where annotated slides will be made available, too. -->

<!-- ## Module 6 -->

<!-- Read: [``Module 6``](../../3-excel/m6-excel/) -->

<!-- Annotate: [``slides``](../../../output/23-Top-M6-lec.pdf) and Excel [`module 6 spreadsheet`](https://canvas.lms.unimelb.edu.au/courses/191080/modules/items/5091456) -->

<!-- Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/153686/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/154246/external_tools/701)). This is where annotated slides will be made available, too. -->



# Additional preparation and resources

## Mandatory

1. [``Spreadsheet for Chapter 3``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/6021476)
1. [``M6.5 spreadsheet``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/6021475) 


## Optional

1. Chapter 5 of @Tay00 (partially relevant).



# Tutorials


Please let us know of any mistake or required update on [``Ed``](https://canvas.lms.unimelb.edu.au/courses/220261/external_tools/5837?display=borderless).

<!-- ## Tutorial materials -->


## This week


Will be announced after the lectures.

<!-- Tutorial exercises in scope this week are -->

<!-- - Pre-tutorials: 6.4.1 (`offset1`), as well as reviewing the lecture's spreadsheet and associated slides (ignore $f(i)$ for now). -->
<!-- - Tutorials: 3.2.1 (`LRcountsxl2`), 3.2.2 (`compareLR1`), and 3.3.1 (`frequency1`). Note that 3.2.1-3.2.2 has to be replicated for three different data sets. It will take you a while to do all of them for the first time! Have the lecture spreadsheet next to it and try to replicate the steps. -->






# Preparation for assessment

 
## Mid-semester (15%) and final (60%) exams

<!-- install.packages("devtools") -->
<!-- devtools::install_github("hadley/emo") -->

- Finalise your summary of Modules 1-3. 
- Work on your [cheat sheet](https://topics-actl.netlify.app/docs/0-subject-guide/assessment/#type)

<!-- Note that all of Modules 1 to 4 are in scope for the [``mid-semester exam``](../../0-subject-guide/assessment//#mid-semester-exam); see also [`this post on Ed`](https://edstem.org/au/courses/12155/discussion/1514408). -->

***Extra consultation hours will be announced***

## Assignment (25%)

- Nothing to do for now, except not fall behind with course materials `r emo::ji("smile")`.
- The assignment will likely be made available in the second half of the subject.


# References