---
bookHidden: true
bookSearchExclude: true
title: "Week 12 Study Plan"
weight: 12
bibliography: ../../../../static/libraries.bib
---


<p style="font-size:18px;font-weight:bold;">Week 12</p> 

<p style="font-size:18px;font-weight:bold;color: rgb(255, 0, 0);"> Please fill out the end of subject survey (ESS) <a href="https://www.unimelb.edu.au/sls/information-for-students/end-of-subject-surveys">here</a>-- thanks in advance!</p>


# Overview

<!-- This week, we will cover the following topics: -->

Continuing on with the Time Series component of the subject, which corresponds to the Section 2 of the CS2 syllabus; In particular, we will

- discuss how to fit the models seen in Module 9 to data sets;
- discuss how to use those fitted models to perform forecasts.


<!-- Here is the end of week 9 video, which introduces week 10: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/89e42857-74c0-4f79-82cb-e32a47e0966a/public?autoplay=false&automute=false"></iframe><!--/html_preserve--> -->

<!-- <p style="font-size:10px;color: rgb(252, 156, 249);"> If you wish to watch the embedded videos from Lecture Capture, you need to have logged in and <a href="https://canvas.lms.unimelb.edu.au/courses/150864/external_tools/701">entered Lecture Capture</a> via Canvas once for each session. This is to restrict access to students enrolled at the University of Melbourne only. </p> -->




See also detailed learning outcomes 2.2.1 and 2.2.4 of the CS2 syllabus [``here``](../../0-subject-guide/SILO).

# Main references and lectures




## Module 10

Read: [``Module 10``](../../1-time-series/m10-estimation-and-forecasting)

Annotate: [``slides``](../../../output/23-GIM-M10-lec.pdf) 
<!-- [``annotated slides``](../../../output/22-GIM-M1-lec_a.pdf) -->

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/150824/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/150864/external_tools/701)). This is where annotated slides will be made available, too.



# Additional preparation and resources

## Mandatory


1. Chapter 3.4, 3.5, and 3.7  of @ShSt17
1. S6 (CS2 Time Series notes)

## Optional

1. n/a



# Tutorials

Note that a full list of exercises is available [``here``](https://canvas.lms.unimelb.edu.au/courses/173733/modules/items/4466801). Please let us know of any mistake or required update on [``Ed``](https://canvas.lms.unimelb.edu.au/courses/173733/external_tools/5601?display=borderless).

## Pre-Tutorial work

Please study those questions **before** the tutorial.

Pre-Tutorial exercises are available in the [``Pre-Tutorial book``](https://canvas.lms.unimelb.edu.au/courses/173733/modules/items/4464391), which already includes solutions. It is recommended to attempt the questions *before* looking at the solutions

## Tutorial materials

Some questions have been especially selected for the tutorials. Students should review and attempt those questions ***prior to their scheduled tutorial***, after they complete the pre-tutorial work. 

The [``Tutorial book``](https://canvas.lms.unimelb.edu.au/courses/173733/modules/items/4464392) includes all questions for the whole semester already, but solutions will only be added sequentially at the end of each week, as we work our way through the set.

Note that solutions will be gradually added to that same document. Hence it is not recommended to print it, as it will regularly change (typos will also dynamically be corrected).

## This week

All of Module 10 is in scope for the tutorials this week. 

<!-- Here is the recording available for Week 12 from William: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/350705e2-7346-44d7-b783-b7a1b2c1ee0d/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve-->  -->

<!-- <!-- Here is the recording available for Week 10 from Eric: --> -->

<!-- <!-- <!--html_preserve--> --> -->
<!-- <!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/cc061437-f56e-481d-8194-48a0c88b80e3/public?autoplay=false&automute=false"></iframe> --> -->
<!-- <!-- <!--/html_preserve--> --> -->

<!-- <p style="font-size:10px;color: rgb(252, 156, 249);"> If you wish to watch the embedded videos from Lecture Capture, you need to have logged in and <a href="https://canvas.lms.unimelb.edu.au/courses/145406/external_tools/701">entered Lecture Capture</a> via Canvas once for each session. This is to restrict access to students enrolled at the University of Melbourne only. </p> -->



## Next week (SWOT-VAC)

This is the last week of teaching. Next week is dedicated to the preparation of exams.



## Additional questions

The "additional questions" are here for reinforcement or revision, but are not the main focus of the tutorials. Solutions for those exercises are already available.


# Preparation for assessment


## Mid-semester (15%) and final (60%) exams

<!-- install.packages("devtools") -->
<!-- devtools::install_github("hadley/emo") -->

Mid-semester exam is done! `r emo::ji("smile")`

For the final exam:

- Finalise your summary of Module 10, and an overview of the time series component of the subject.
- Review the additional consultation times organised for the exam preparation (if not available yet, they will be soon!)
- Closer to the exam, try the practice exams.


## Assignment (25%)


- The assignment is being marked. Results will be available this week (12).

# References