---
bookHidden: true
bookSearchExclude: true
title: "Week 9 Study Plan"
weight: 9
bibliography: ../../../../static/libraries.bib
---


<p style="font-size:18px;font-weight:bold;">Week 9</p> 

# Overview

<p style="font-size:16px;color: rgb(255, 0, 0);"> Note that there is no face to face lecture this week due to unexpected circumstances. Please watch the recorded lectures from Lecture Capture. Thanks for your understanding! </p>
<!-- This week, we will cover the following topics: -->

Continuing on with the Time Series component of the subject, which corresponds to the Section 2 of the CS2 syllabus; In particular, 

- We will revisit regression from the time series context (TS 2.1)
- We will see how to explore data, and try to "detrend" a time series (TS 2.2)
- We will discuss how to use smoothing techniques to gather some more information about the "shape" of the time series, such as cycles (TS 2.3)

Here is the end of week 8 video, which introduces week 9:

<!--html_preserve-->
<iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/7a92c667-fd05-4680-a855-83f981633864/public?autoplay=false&automute=false"></iframe>
<!--/html_preserve-->

<p style="font-size:10px;color: rgb(252, 156, 249);"> If you wish to watch the embedded videos from Lecture Capture, you need to have logged in and <a href="https://canvas.lms.unimelb.edu.au/courses/150864/external_tools/701">entered Lecture Capture</a> via Canvas once for each session. This is to restrict access to students enrolled at the University of Melbourne only. </p>




See also detailed learning outcomes 2.2.1-2.1.2 and 2.2.1 of the CS2 syllabus [``here``](../../0-subject-guide/SILO).



# Main references and lectures


## Module 8

Read: [``Module 8``](../../1-time-series/m8-regressions-eda/)

Annotate: [``slides``](../../../output/23-GIM-M8-lec.pdf) 
<!-- [``annotated slides``](../../../output/22-GIM-M1-lec_a.pdf) -->

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/150824/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/150864/external_tools/701)). This is where annotated slides will be made available, too.





# Additional preparation and resources

## Mandatory

1. Chapter 2.1-2.3 of @ShSt17


## Optional

1. n/a



# Tutorials

Note that a full list of exercises is available [``here``](https://canvas.lms.unimelb.edu.au/courses/173733/modules/items/4466801). Please let us know of any mistake or required update on [``Ed``](https://canvas.lms.unimelb.edu.au/courses/173733/external_tools/5601?display=borderless).

## Pre-Tutorial work

Please study those questions **before** the tutorial.

Pre-Tutorial exercises are available in the [``Pre-Tutorial book``](https://canvas.lms.unimelb.edu.au/courses/173733/modules/items/4464391), which already includes solutions. It is recommended to attempt the questions *before* looking at the solutions

## Tutorial materials

Some questions have been especially selected for the tutorials. Students should review and attempt those questions ***prior to their scheduled tutorial***, after they complete the pre-tutorial work. 

The [``Tutorial book``](https://canvas.lms.unimelb.edu.au/courses/173733/modules/items/4464392) includes all questions for the whole semester already, but solutions will only be added sequentially at the end of each week, as we work our way through the set.

Note that solutions will be gradually added to that same document. Hence it is not recommended to print it, as it will regularly change (typos will also dynamically be corrected).

## This week

All of Module 8 is in scope for the tutorials this week. 

<!-- Here is the recording available for Week 9 from William: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/f4a2bd86-0869-4b53-adfd-fd64c05f411e/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve--> -->

<!-- Here is the recording available for Week 9 from Eric: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/4c5f4937-29db-4159-9a4b-a65b98f9ce18/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve--> -->

<!-- <p style="font-size:10px;color: rgb(252, 156, 249);"> If you wish to watch the embedded videos from Lecture Capture, you need to have logged in and <a href="https://canvas.lms.unimelb.edu.au/courses/145406/external_tools/701">entered Lecture Capture</a> via Canvas once for each session. This is to restrict access to students enrolled at the University of Melbourne only. </p> -->


## Next week (week 10)

Next week, we will discuss Module 9, Sections 1-3.



## Additional questions

The "additional questions" are here for reinforcement or revision, but are not the main focus of the tutorials. Solutions for those exercises are already available.


# Preparation for assessment


## Mid-semester (15%) and final (60%) exams

<!-- install.packages("devtools") -->
<!-- devtools::install_github("hadley/emo") -->

Mid-semester exam is done! `r emo::ji("smile")`

For the final exam:

- Finalise your summary of Module 7.
- Start your summary of Module 8.


## Assignment (25%)

- This week you should be polishing your presentation. Get feedback from friends. Re-record it after you got some feedback.
- The presentation is ***due next week***! (Thursday 11 May 11.05am sharp)

# References