---
weight: 30
title: Prerequisite Knowledge
bibliography: ../../../static/libraries.bib
header-includes:
   - \usepackage{actuarialsymbol}
   - \usepackage{amsmath}
---


```{r setup, include=FALSE}
library(knitr)
options(width = 70) 
```

<p style="font-size:18px;font-weight:bold;">Summary of some of the prerequisite knowledge required for this subject:</p> 

 

# Excel

To view the eligibility and requirements, including prerequisites, corequisites, recommended background knowledge and core participation requirements for this subject, please see the University Handbook: 
https://handbook.unimelb.edu.au/2024/subjects/actl20004/eligibility-and-requirements

Excel assumed knowledge
Because everyone has used Excel before, a challenge in this subject is to start at the right level of assumed knowledge. We had to strike a balance between (i) not assuming so much that it is too much work to catch up if you have little experience, and (ii) not assuming enough that no-one draws benefits from the subject, and is bored to death. Below, you will find reference to those topics that we will assume are prior knowledge. Numbers correspond to Chapters of @EE19 (see “Subject Resources” below).

It is strongly recommended that you review those topics, including, but not limited to, those “semi-beginner” topics that are singled out with bullet points. 

Ch. 1: Becoming Acquainted with Excel  

Ch. 2: Navigating and Working with Worksheets  

Ch. 3: Best Ways to Enter and Edit Data  

  -  Autofill: P. 105-116, and p. 298-301  
  
Ch. 4: Formatting and Aligning Data  

  -  Format Painter: 178-181
  
Ch. 5 Different Ways of Viewing and Printing Your Workbook  

Ch. 6 Understanding Backstage  

  -  Freezing rows and columns: 221
  
Ch. 7 Creating and Using Formulas  

  -  Named ranges and constants: 312-332
  
  -  Absolute and mixed cell references ($): 332-342
  
Ch. 8: Excel’s Pre-existing Functions  

  -  All important
  -  New Excel 2019 functions (IFS, MAXIFS, MINIFS): p. 381-398
  
Ch. 9: Auditing, Validating, and Protecting Your Data  

  -  Error Value Messages: p. 432
  -  Formula Auditing: p. 436-439
  
Ch. 10: Using Hyperlinks, Combining Text, and Working with the Status Bar   

  -  Concatenation: p. 475-485
  
Ch. 11: Transferring and Duplicating Data to Other Locations   

  -  Paste special (including with “Transpose”): p. 518-530
  
Ch. 12: Working with Tables  

  -  Conditional formatting: p.569-581
  
Ch. 13: Working with Charts  

  -  Sparklines: p. 656-664
  
Ch. 14: Importing Data  


\_

*Reference:*