---
weight: 4
title: "Resources"
---


# Website


The current website contains (or links) to all the resources you need for the course (compare the following list with left hand side menu):

- [Subject guide](../) (you are reading it!)
- [Prerequisite knowledge](../../0-prerequisite-knowledge/): assumed knowledge in Excel
- [Utility theory (CM2 1.2)](../../1-utility/): the contents covering Section 1.2 of the CM2 syllabus.
- [Reserving (CM2 5.2)](../../2-reserving/): the contents covering Section 5.2 of the CM2 syllabus.
- [Excel (CM2 Exam B)](../../3-excel/): the contents covering the Excel component of the CM2 syllabus.
- [Stochastic interest (CM2 3)](../../4-stochastic-interest/): the contents covering Section 3 of the CM2 syllabus.
- [Ruin Theory (CM2 5.1 5.3)](../../5-ruin-theory/): the contents covering Section 5.1 and 5.3 of the CM2 syllabus.
- [Ed discussion forum](https://canvas.lms.unimelb.edu.au/courses/173733/external_tools/5601?display=borderless): link to the main interaction fora
- [Tutorial exercises](): to be discussed in tutorials. Solutions will be posted at the end of the relevant week.

Details about assessment will be available under [Subject Guide / Assessment](../Assessment)



# Prescribed readings

Prescribed references are:

- [Joshi] For Module 1 (Chapters 7 and 8)
Joshi, M., Paterson, J. M. (2013), Introduction to Mathematical Portfolio Theory, Cambridge University Press, ISBN 9781107042315
- [Taylor] For Modules 2-5 (Chapters 1 to 5)
Taylor, G. (2000) Loss Reserving: An Actuarial Perspective Huebner International Series on Risk, Insurance and Economic Security (HSRI volume 21) https://link.springer.com/book/10.1007/978-1-4615-4583-5  
- [EE19] For Excel
Slager, D., Slager, A. (2020) Essential Excel 2019 Apress, 2nd Edition, ISBN 978-1-4842-6208-5, https://doi.org/10.1007/978-1-4842-6209-2 
- [AE23] For Excel
Katz, A. I. (2023) Up Up and Array! Dynamic Array Formulas for Excel 365 and Beyond,  Apress, ISBN 978-1-4842-8965-5, https://doi.org/10.1007/978-1-4842-8966-2 
- [Dickson] 
Dickson, D. C. M. (2016) Insurance Risk and Ruin, 2nd Edition, Cambridge University Press, https://doi.org/10.1017/9781316650776

Most of those references can be downloaded from the [Readings Online](https://canvas.lms.unimelb.edu.au/courses/220261/external_tools/1188) section of the Canvas community website.

