---
bookHidden: false
bookSearchExclude: false
title: "Week 6 Study Plan"
weight: 6
bibliography: ../../../../static/libraries.bib
---


<p style="font-size:18px;font-weight:bold;">Week 6</p> 

# Overview

<!-- This week, we will cover the following topics: -->
This week, we have a lecture on Monday, the [``mid-semester exam``](https://topics-actl.netlify.app/docs/0-subject-guide/assessment/#mid-semester-exam) on Wednesday, and the remainder of tutorials for Modules 4/5/6 on Friday. This is the last week I'll be teaching this semester!


In the lecture and tutorials, we will cover the following topics:

- This week (for Module 4) we focus on the Payment Per Claim Incurred (PPCI) method, which is somewhat akin to the Exposure methods for counts.
- There are some slides with the main elements, but major components of the module is with two spreadsheets, which can be downloaded [``here for Chapter 3``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/6021476) and [``here for the PPCI method``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/6021477)
- Module 5 discusses how to make a choice / combine diverging results from different reserving methods, and also introduced the Bornhuetter-Ferguson method, which typically deals with highly leveraged triangles for their most immature years.
- In Excel, we discuss simulation, how to implement that in Excel, and also Macros. You will discuss simulation more with Yuyu.





See also detailed learning outcomes of 5.2 ("Liability valuations / Run-off triangles") of the CM2 syllabus, as well as CM2-B Excel examinations [``here``](../../0-subject-guide/SILO).



# Main references and lectures


<p style="font-size:12px;color: rgb(255, 0, 0);">Note: Typos and issues are being updated continuously throughout the semester. The online notes are always up-to-date, and can easily be read on a mobile device (version date is at the bottom). If you download a pdf version of the slides, a version date is also available on the first page. If you click on the link "latest slides" you will download the latest version. You can then compare the date and work out if it was updated. </p>



## Module 4


Read: [``Module 4``](../../2-reserving/m4-reserving-claim-amounts/)

Annotate: [``slides``](../../../output/24-Top-M4-lec.pdf) [``Spreadsheet for the PPCI method``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/6021477)

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/183926/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/181779/external_tools/701)). This is where annotated slides will be made available, too.


## Module 5

Read: [``Module 5``](../../2-reserving/m5-reserving-combination/)

Annotate: [``slides``](../../../output/24-Top-M5-lec.pdf)

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/183926/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/181779/external_tools/701)). This is where annotated slides will be made available, too.



## Module 6: Excel

Read: [``Module 6: Excel topics``](../../3-excel/m6-excel)

Annotate: [``slides``](../../../output/24-Top-M6-lec.pdf) [``spreadsheet``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/6034154) 
[``annotated slides UG``](https://canvas.lms.unimelb.edu.au/courses/183926/modules) [``annotated slides PG``](https://canvas.lms.unimelb.edu.au/courses/181779/modules)

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/183926/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/181779/external_tools/701)). This is where annotated slides will be made available, too.





# Additional preparation and resources


## Mandatory

1. [``Spreadsheet for the PPCI method``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/6021477)
1. [``M6.6 spreadsheet``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/6034154) 


## Optional

1. Chapter 5 of @Tay00 (partially relevant).





# Tutorials


Please let us know of any mistake or required update on [``Ed``](https://canvas.lms.unimelb.edu.au/courses/220261/external_tools/5837?display=borderless).
<!-- ## Tutorial materials -->


## This week


Will be announced after the lectures.

<!-- Tutorial exercises in scope this week are -->

<!-- - Pre-tutorials: 6.5.1 (`etiquette1xl`), as well as reviewing the lecture's spreadsheet and associated slides. -->
<!-- - Tutorials: 4.1.1 (`LRamounts1`), 4.2.1 (`LRamounts2`), and 4.2.2 (`LRamounts3`).  -->




# Preparation for assessment


## Mid-semester (15%) and final (60%) exams

<!-- install.packages("devtools") -->
<!-- devtools::install_github("hadley/emo") -->


- Finalise your summary of Modules 1-4. 
- Work on your [cheat sheet](https://topics-actl.netlify.app/docs/0-subject-guide/assessment/#type)
- Review the information about the [``mid-semester exam``](https://topics-actl.netlify.app/docs/0-subject-guide/assessment/#mid-semester-exam). 


<!-- Information about the mid-semester exam is available [`here and in the links therein`](https://edstem.org/au/courses/12155/discussion/1531072). -->


## Assignment (25%)

- Nothing to do for now, except not fall behind with course materials `r emo::ji("smile")`.
- The assignment will likely be made available in the second half of the subject.


# References