---
weight: 2
title: "Learning Outcomes"
---

# Subject Intended Learning Outcomes (SILO)

To view the subject objectives and the generic skills you will develop through successful completion of this subject, please see the University Handbook.

## ACTL20004 SILO

The ACTL20004 subject intended learning outcomes (SILO) are as follows:

1.	Derive and apply results for simple stochastic models for investment returns.
2.	Describe and apply techniques for analysing a delay (or run-off) triangle and projecting the ultimate position.
3.	Illustrate the concept of ruin and analyse the significance of the adjustment coefficient in ruin theory.
4.	Use utility theory to describe the main aspects of risk and insurance.
5.	Build and manipulate financial models in spreadsheet software.
6.	Apply pre-requisite mathematical and statistical concepts to the solution of problems on the above topics.


## ACTL90021 SILO

The ACTL90021 subject intended learning outcomes (SILO) are as follows:

1.	Critically review simple stochastic models for investment returns.
2.	Compose and assess techniques for analysing a delay (or run-off) triangle and projecting the ultimate position.
3.	Elucidate the concept of ruin and commentate on the significance of the adjustment coefficient in ruin theory.
4.	Contextualise the main aspects of risk and insurance using utility theory.
5.	Compose and transform financial models in spreadsheet software.
6.	Compose pre-requisite mathematical and statistical concepts to solve problems related to the above topics.



# Mapping to the IFoA Financial Engineering and Loss Reserving (CM2) subject

This subject is one of three subjects covering the contents of the [CM2 “Financial Engineering and Loss Reserving” subject of the Institute and Faculty of Actuaries](https://www.actuaries.org.uk/documents/cm2-syllabus-2023). This counts towards the [“Foundation Program” of the Australian Actuaries Institute professional curriculum and syllabus](https://actuaries.asn.au/education-program/foundation). 

In particular, ACTL20004/90021 is meant to cover Items 1.2, 3 and 5 of the CM2 syllabus. This is detailed in the following table, with mapping towards the course modules (and major reference in parentheses; see “Subject Resources” below), as well as subject intended learning outcomes (SLO).

A detailed mapping is available in the subject guides - [UG](https://canvas.lms.unimelb.edu.au/courses/183926/modules/items/5934974),[PG](https://canvas.lms.unimelb.edu.au/courses/181779/modules/items/5934975)
