---
bookHidden: false
bookSearchExclude: false
title: "Week 1 Study Plan"
weight: 1
bibliography: ../../../../static/libraries.bib
---


<p style="font-size:18px;font-weight:bold;">Week 1</p> 

# Overview


This week, we will cover the following topics:

- Introduction to the course: what are the topics we will cover in this subject, and how are they connected?
- Risk and Insurance (Module 1.1-1.3): to put it in the way the CM2 notes puts it, how do we model the behaviours of agents on a market? What is a possible mathematical model for "rational" behaviour, that could explain why people purchase insurance?
- We will also introduce the Excel component of the subject (Module 6.1)

See also detailed learning outcomes of 1.2 (utility theory) of the CM2 syllabus [``here``](../../0-subject-guide/SILO).

<!-- # Videos -->

<!-- Here is the week 1 video introduction. In this video I briefly introduce myself, the subject, and highlight some key aspect of the 2023 delivery and differences with previous years. -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/faeb16b3-0ff2-4335-98fa-fde57450bfb3/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve--> -->

<!-- Furthermore, here is a video with detailed overview of the course resources and organisation: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/0a8d1f59-14ed-4003-b986-d652306668b1/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve--> -->

<!-- <p style="font-size:10px;color: rgb(252, 156, 249);"> If you wish to watch the embedded videos from Lecture Capture, you need to have logged in and <a href="https://canvas.lms.unimelb.edu.au/courses/150864/external_tools/701">entered Lecture Capture</a> via Canvas once for each session. This is to restrict access to students enrolled at the University of Melbourne only. </p> -->





# Main references and lectures

## Prerequisite knowledge

Please review the [``Prerequisite knowledge``](../../0-prerequisite-knowledge/) page for this course. This is not exhaustive by any means, but provides minimum knowledge you should be comfortable with. Note that Tutorials in Week 1 are your opportunity to ask about those topics.


## Module 1: Utility, Risk and Insurance

Read: [``Module 1: Utility, Risk and Insurance``](../../1-utility/m1-risk-insurance/)

Annotate: [``slides``](../../../output/23-Top-M1-lec.pdf) 
<!-- [``annotated slides``](../../../output/22-GIM-M1-lec_a.pdf) -->

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/183926/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/181779/external_tools/701)). This is where annotated slides will be made available, too.

## Module 6: Utility, Risk and Insurance

Read: [``Module 6: Excel topics``](../../3-excel/m6-excel)

Annotate: [``slides``](../../../output/24-Top-M6-lec.pdf) 
<!-- [``annotated slides``](../../../output/22-GIM-M1-lec_a.pdf) -->

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/183926/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/181779/external_tools/701)). This is where annotated slides will be made available, too.


# Additional preparation and resources

## Mandatory

1. Read the [``Subject Guide``](../../0-subject-guide).
1. Review the [``prerequisite knowledge``](../week-1/#prerequisite-knowledge).
1. Chapter 7.1-7.3 and 8.1-8.3 of @Jos13 (for Module 1)


## Optional

1. Unit 2 of @IoA23
1. Chapter 2 of @Dic16



# Tutorials

Please let us know of any mistake or required update on [``Ed``](https://canvas.lms.unimelb.edu.au/courses/220261/external_tools/5837?display=borderless).

<!-- ## Pre-Tutorial work -->

<!-- Please study those questions **before** the tutorial. -->

<!-- Pre-Tutorial exercises are available in the [``Pre-Tutorial book``](https://canvas.lms.unimelb.edu.au/courses/173733/modules/items/4464391), which already includes solutions. It is recommended to attempt the questions *before* looking at the solutions -->

## Tutorial materials

<!-- Some questions have been especially selected for the tutorials. Students should review and attempt those questions ***prior to their scheduled tutorial***, after they complete the pre-tutorial work.  -->

<!-- The [``Tutorial book``]() includes all questions for the whole semester already, but solutions will only be added sequentially at the end of each week, as we work our way through the set. -->

<!-- Note that solutions will be gradually added to that same document. Hence it is not recommended to print it, as it will regularly change (typos will also dynamically be corrected). -->

## This week

To be announced after the lectures.

<!-- Tutorial exercises in scope this week are Sections 1.1 to 1.3, minus utilins3 (exercise 1.3.5). The two last exercises (`utilins3` and `util8`) will be covered next week. -->




<!-- Here is the recording available for Week 1 from William: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/986498e7-d7fa-42c4-8af0-492f068f4ccd/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve--> -->

<!-- Here is the recording available for Week 1 from Eric: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/a5dc442a-1e84-49c8-b317-3f4eb4c1cfa0/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve--> -->


<!-- <p style="font-size:10px;color: rgb(252, 156, 249);"> If you wish to watch the embedded videos from Lecture Capture, you need to have logged in and <a href="https://canvas.lms.unimelb.edu.au/courses/145406/external_tools/701">entered Lecture Capture</a> via Canvas once for each session. This is to restrict access to students enrolled at the University of Melbourne only. </p> -->


## Next week (week 2)
 
To be announced after the lectures.

<!-- The two last exercises of Module ` (`utilins3` and `util8`) will be covered next week. Also, we will start on Loss Reserving and will discuss Modules 2 (and possibly 3). -->



<!-- ## Additional questions -->

<!-- The "additional questions" are here for reinforcement or revision, but are not the main focus of the tutorials. Solutions for those exercises are already available. -->

# Preparation for assessment

 
## Mid-semester (15%) and final (60%) exams

<!-- install.packages("devtools") -->
<!-- devtools::install_github("hadley/emo") -->

- Nothing to do for now - just don't fall behind `r emo::ji("smile")`.  

<!-- devtools::install_github("hadley/emo") -->


## Assignment (25%)

- Nothing to do for now.


# References