---
bookHidden: false
bookSearchExclude: false
title: "Week 2 Study Plan"
weight: 2
bibliography: ../../../../static/libraries.bib
---


<p style="font-size:18px;font-weight:bold;">Week 2</p> 

# Overview


This week, we will cover the following topics:

- End of Module 1 (characterising risk aversion, and additional considerations)
- Module 2, which introduces the basics of loss reserving: what it is, why it matters, notation, data
- Module 6.2, which looks at data cleaning, wrangling, and pivot tables.

See also detailed learning outcomes of 1.2 ("Rational choice theory") and 5.2 ("Liability valuations / Run-off triangles") of the CM2 syllabus [``here``](../../0-subject-guide/SILO).

<!-- Here is the end of week 1 video, which introduces week 2: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/2082fb0b-ecb8-41ba-9937-27b1048f9c06/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve--> -->

<!-- <p style="font-size:10px;color: rgb(252, 156, 249);"> If you wish to watch the embedded videos from Lecture Capture, you need to have logged in and <a href="https://canvas.lms.unimelb.edu.au/courses/150864/external_tools/701">entered Lecture Capture</a> via Canvas once for each session. This is to restrict access to students enrolled at the University of Melbourne only. </p> -->








# Main references and lectures

<p style="font-size:12px;color: rgb(255, 0, 0);">Note: Typos and issues are being updated continuously throughout the semester. The online notes are always up-to-date, and can easily be read on a mobile device (version date is at the bottom). If you download a pdf version of the slides, a version date is also available on the first page. If you click on the link "latest slides" you will download the latest version. You can then compare the date and work out if it was updated. </p>

## Module 1: Utility, Risk and Insurance

Read: [``Module 1: Utility, Risk and Insurance``](../../1-utility/m1-risk-insurance/)

Annotate: [``slides``](../../../output/24-Top-M1-lec.pdf) 
[``annotated slides UG``](https://canvas.lms.unimelb.edu.au/courses/183926/modules) [``annotated slides PG``](https://canvas.lms.unimelb.edu.au/courses/181779/modules)

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/183926/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/181779/external_tools/701)). This is where annotated slides will be made available, too.

## Module 2: Basic Reserving Concepts

Read: [``Module 2: Basic Reserving Concepts``](../../2-reserving/m2-basic-reserving-concepts/)

Annotate: [``slides``](../../../output/24-Top-M2-lec.pdf) 
[``annotated slides UG``](https://canvas.lms.unimelb.edu.au/courses/183926/modules) [``annotated slides PG``](https://canvas.lms.unimelb.edu.au/courses/181779/modules)

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/183926/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/181779/external_tools/701)). This is where annotated slides will be made available, too.


## Module 6: Excel

Read: [``Module 6: Excel topics``](../../3-excel/m6-excel)

Annotate: [``slides``](../../../output/24-Top-M6-lec.pdf) [``spreadsheet``](https://canvas.lms.unimelb.edu.au/courses/220261/modules/items/5960390) 
[``annotated slides UG``](https://canvas.lms.unimelb.edu.au/courses/183926/modules) [``annotated slides PG``](https://canvas.lms.unimelb.edu.au/courses/181779/modules)

Watch: refer to your lecture recording under "Lecture Capture" ([``UG``](https://canvas.lms.unimelb.edu.au/courses/183926/external_tools/701)/[``PG``](https://canvas.lms.unimelb.edu.au/courses/181779/external_tools/701)). This is where annotated slides will be made available, too.


# Additional preparation and resources

## Mandatory

1. Chapter 7.1-7.3 and 8.1-8.3 of @Jos13 (for Module 1)
1. Chapter 1 of @Tay00 (for Module 2)

## Optional

1. Unit 2 of @IoA23
1. Chapter 2 of @Dic16
1. Unit 5 of @IoA23



# Tutorials

Please let us know of any mistake or required update on [``Ed``](https://canvas.lms.unimelb.edu.au/courses/220261/external_tools/5837?display=borderless).

<!-- ## Pre-Tutorial work -->

<!-- Please study those questions **before** the tutorial. -->

<!-- Pre-Tutorial exercises are available in the [``Pre-Tutorial book``](https://canvas.lms.unimelb.edu.au/courses/173733/modules/items/4464391), which already includes solutions. It is recommended to attempt the questions *before* looking at the solutions -->

## Tutorial materials

<!-- Some questions have been especially selected for the tutorials. Students should review and attempt those questions ***prior to their scheduled tutorial***, after they complete the pre-tutorial work.  -->

The [``Tutorial book``]() includes all questions for the whole semester already, but solutions will only be added sequentially at the end of each week, as we work our way through the set.

Note that solutions will be gradually added to that same document. Hence it is not recommended to print it, as it will regularly change (typos will also dynamically be corrected).

## This week

Tutorial exercises in scope this week are the two last exercises (`utilins3` and `util8`) of Module 1, as well as Module 2.

<!-- Here is the recording available for Week 1 from William: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/986498e7-d7fa-42c4-8af0-492f068f4ccd/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve--> -->

<!-- Here is the recording available for Week 1 from Eric: -->

<!-- <!--html_preserve--> -->
<!-- <iframe height="420" width="640" allowfullscreen frameborder=0 src="https://echo360.net.au/media/a5dc442a-1e84-49c8-b317-3f4eb4c1cfa0/public?autoplay=false&automute=false"></iframe> -->
<!-- <!--/html_preserve--> -->


<!-- <p style="font-size:10px;color: rgb(252, 156, 249);"> If you wish to watch the embedded videos from Lecture Capture, you need to have logged in and <a href="https://canvas.lms.unimelb.edu.au/courses/145406/external_tools/701">entered Lecture Capture</a> via Canvas once for each session. This is to restrict access to students enrolled at the University of Melbourne only. </p> -->


## Next week (week 3)
 
We will move on to Module 3 (and perhaps 4).



# Preparation for assessment


## Mid-semester (15%) and final (60%) exams

<!-- install.packages("devtools") -->
<!-- devtools::install_github("hadley/emo") -->

- Start your summary of Module 1.

## Assignment (25%)

- Nothing to do for now.


# References